platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do

  pod 'Desk360', :path => '..'
  # pod 'PersistanceKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "10.0"
    end
  end
end
