platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do

  pod 'Desk360', :path => '..'
  # pod 'PersistanceKit'
  pod 'LookinServer', :configurations => ['Debug']
end
